### ISSUE TITLE
How does pynrrd relate to mhe/pynrrd

### ISSUE THREAD

**Issue by samueljohn** [sinkpoint/pynrrd#1]
Any reason to have two repositories?
Is this a fork of @mhe's pynrrd? It is not marked as such. The author has been replaced (by accident?)

Looks like you added tests here. Perhaps open a PR to upstream then?
- https://github.com/mhe/pynrrd

**Comment by mhe** [comment]
From the looks of it this is not a fork of my pynrrd bit simply a project with the same name (and similar purpose).

**Comment by sinkpoint** [comment]
Yes, this is my own library for nrrd i/o in python. 
I was not aware of the existence of another pynrrd until now.

**Comment by samueljohn** [comment]
Thanks for clearing this up.
